# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev

WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY README.md .
COPY LICENSE .
COPY src/ src/

# Upgrade pip and install the package
RUN pip install --upgrade pip && \
    pip install .

# Expose MCP server via the entrypoint command
ENTRYPOINT ["oura-mcp-server"]
